source 'http://rubygems.org'

gem 'rails', '4.0.2'
gem "protected_attributes"
gem "turbolinks"

platform :ruby do
  gem 'sqlite3'
end
platform :jruby do
  gem 'activerecord-jdbcsqlite3-adapter'
end

gem "hobo_support", :path => "../.."
gem "hobo_fields", :path => "../.."
gem "dryml", :path => "../.."
gem "hobo", :path => "../.."
gem "hobo_rapid", :path => "../.."
gem "hobo_clean", :path => "../.."
gem "hobo_jquery", :path => "../.."
gem "hobo_jquery_ui", :path => "../.."
gem "jquery-ui-themes", "~> 0.0.4"
gem "will_paginate", :git => "git://github.com/Hobo/will_paginate.git"
gem "kramdown"
gem "RedCloth"
gem "shoulda", :group => :test
gem "factory_girl_rails", :group => :test

group :development, :test do
  gem 'capybara', :git => 'git://github.com/jnicklas/capybara.git'
  gem 'database_cleaner'
  gem 'selenium-webdriver', '~> 2.39.0'
  gem 'rubyzip', '~> 1.1.0'
  gem 'debugger'
end

gem "jquery-rails"
gem 'paperclip',     '~> 2.7'   # for 1.8.7 compatibility
gem 'hobo_paperclip', :git => "git://github.com/Hobo/hobo_paperclip.git", :branch => "master"
gem 'acts_as_list'

group :assets do
  gem 'sass-rails',   '~> 4.0.0'
  gem 'coffee-rails', '~> 4.0.0'
  gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
end

gem 'awesome_print'
gem "hobo_simple_color", :git => "git://github.com/Hobo/hobo_simple_color"
gem "hobo_tokeninput", :git => "git://github.com/Hobo/hobo_tokeninput"
