source 'http://rubygems.org'

gem 'rails', '4.0.2'

platform :ruby do
  gem 'sqlite3'
end
platform :jruby do
  gem 'activerecord-jdbcsqlite3-adapter'
end

group :development do
  gem 'debugger'
end

gem "hobo_support", :path => "../.."
gem "hobo_fields", :path => "../.."
gem "dryml", :path => "../.."
gem "hobo", :path => "../.."
gem "hobo_rapid", :path => "../.."
gem "hobo_clean", :path => "../.."
gem "hobo_jquery", :path => "../.."
gem "hobo_jquery_ui", :path => "../.."
gem "jquery-ui-themes", "~> 0.0.4"
gem "will_paginate", :git => "git://github.com/Hobo/will_paginate.git"
gem "kramdown"
gem "RedCloth"
gem "shoulda", :group => :test
gem "factory_girl_rails", :group => :test

group :development, :test do
  gem 'capybara', :git => 'git://github.com/jnicklas/capybara.git'#, :ref => "83d8574c1d"  #"756ec1b2af70c66093c3b25976f520a3e6c3c2ae"
  gem 'database_cleaner'
  gem 'selenium-webdriver'
end

gem "jquery-rails"
gem 'paperclip'
gem 'hobo_paperclip', :git => "git://github.com/Hobo/hobo_paperclip.git", :branch => "master"
gem 'acts_as_list'
gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'
gem 'awesome_print'
gem "hobo_simple_color", :git => "git://github.com/Hobo/hobo_simple_color"
gem "hobo_tokeninput", :git => "git://github.com/Hobo/hobo_tokeninput"
gem "turbolinks"
gem "protected_attributes"